### ISSUE TITLE
Possible to not report status twice

### ISSUE THREAD

**Issue by mrchief** [aslafy-z/conventional-pr-title-action#17]
Is it possible to not show the first status? It really is not a status but shows up because the actual status (the 2nd one) uses a different context than the first (I guess).

![image](https://user-images.githubusercontent.com/781818/74276638-1a8e2880-4ce4-11ea-9c59-344a5734b8db.png)

**Comment by derberg** [comment]
@mrchief I bielieve it is done this way because of this issue https://github.community/t5/GitHub-Actions/duplicate-checks-on-pull-request-event/td-p/33157 and this https://github.com/amannn/action-semantic-pull-request/issues/5#issue-555290040

with approach implemented by this action you at least get a one check that can be set in branch protection and be happy :)

**Comment by mrchief** [comment]
I checked those 2 issues but I'm not sure if we need to do the same everywhere. As long as you report the status using the same [`context`](https://developer.github.com/v3/repos/statuses/#parameters), you should be fine. 

> with approach implemented by this action you at least get a one check that can be set in branch protection and be happy :)

Not really as it is confusing. The first check is bogus and should not be a required check. 

I'm using several other actions which don't have this issue. And if you look deeply into the linked issues, I'm sure the root cause would be something else.

**Comment by derberg** [comment]
Using the same context doesn't solve much. I can still have `required` set to the "custom status" but the other checks are visible too and they are growing and stay there if I only do edit of the title of the PR in the UI. If I do changes to the PR with git push, there are no duplicates

<img width="663" alt="Screenshot 2020-03-05 at 13 59 14" src="https://user-images.githubusercontent.com/6995927/75983881-a4976e80-5ee9-11ea-8cca-34ea20acaa8f.png">

**Comment by derberg** [comment]
I test things here on this PR https://github.com/derberg/generator/pull/2 and play with config here https://github.com/derberg/generator/blob/conventional-commits/.github/workflows/pr.yml

**Comment by aslafy-z** [comment]
@mrchief: AFAIK, this is the only solution for allowing users to use a required check out of this action. If we use the same context name, all the checks are required to pass, even the old ones. 
I did this few times ago, might need another testing, but this is why I decided to use that path. I've seen your repo, I guess you can update your events to only keep `opened` and `edited`.
Can you link me to others actions that reacts on edit event like this one?

**Comment by mrchief** [comment]
@aslafy-z I've been digging around with this and this one does seem to be an issue, especially if you do POST or use `core.setMessage`. The other actions I was referring to do neither of those. They probably set exit codes and that seems to be OK. There are talks about moving over to Checks API but that API is not as straightforward as Status API.

**Comment by derberg** [comment]
fyi, current approach makes the action not usable in a workflow where contributions come from forks. If the PR is opened from a fork, for security reason GITHUB_TOKEN is read-only, so PR validation fails as POST operation fails

**Comment by nZeus** [comment]
Also, the second link points to this repository, instead of pointing to the "check" itself.

![image](https://user-images.githubusercontent.com/2727326/96140179-f2ed0100-0eff-11eb-8c28-360ca0a0f4a2.png)
---

The action should be displayed once (as a single check), and the link should refer to the "GH Actions" page

**Comment by DanielHabenicht** [comment]
> fyi, current approach makes the action not usable in a workflow where contributions come from forks. If the PR is opened from a fork, for security reason GITHUB_TOKEN is read-only, so PR validation fails as POST operation fails

You can use the `pull_request_target` instead of `pull_request` to circumvent that (see here: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target)

**Comment by Tbhesswebber** [comment]
I've never manually reported back to the repo using an octocat client instance when I've written JS actions as mandatory checks.  My best guess is that the double report is due to the fact that this action sets the status manually using `client.request` and, if the check is required to pass on a specific branch, implicitly just by existing.

I would recommend dropping the manual call to the status endpoint and rely on consumers to understand how to configure protected branches and required status checks

**Comment by aslafy-z** [comment]
I will close this issue since the repository is now archived. There are some alternatives out there, https://github.com/amannn/action-semantic-pull-request being one of them. Thank you for your understanding.
